[package]
name = "chip-8"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
rand = "0.9.2"

[dependencies.windows]
version = "0.62.1"
features = [
  "Win32_UI_Input_KeyboardAndMouse",
]
